---
title: "Chickwts Analysis"
author: "Alreaan, Abdullah"
date: "Oct, 2020"
output: html_document
---
 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(magrittr)
library(knitr)
library(DT)
library(ggplot2)
```

## Descriptive Statistics



```{r, echo= FALSE}
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)
chiktbl <- chickwts %>%
           dplyr:: group_by(feed) %>%
           dplyr:: summarise(n = n(),
            average = mean(weight),
            SD = sd(weight))
 

```


```{r, echo=FALSE}
library(DT)
DT::datatable(chiktbl)

```
## Plots



```{r, echo=FALSE}
ggplot (chickwts, aes(feed, weight))+
  geom_boxplot()

 ggplot (chickwts, aes(feed, weight)) +
  geom_jitter(width = 0.2, shape = 16, alpha = 0.75) +
  stat_summary(fun.data = mean_sdl, fun.args = list(mult = 1), col = "red")
```

## Inferential Statistics
The one-way ANOVA summary:

```{r, echo=FALSE}
chickwts.lm <- lm(weight ~ feed, data=chickwts)
  chickwts.ano <- anova(chickwts.lm)
  
```
```{r, echo=FALSE}
library(DT)
DT::datatable(chickwts.ano)

```
Tukey’s Post-hoc test:

```{r, echo=FALSE}
 chickwts.av <- aov(weight ~ feed, data = chickwts)
  tukeyTest <- TukeyHSD(chickwts.av)
  
  datatable(tukeyTest$feed)

```
